CREATE TABLE IF NOT EXISTS parkings (
id_par SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
location VARCHAR(255) NOT NULL,
total_spots INT NOT NULL,
created_at TIMESTAMP NULL DEFAULT current_timestamp,
updated_at TIMESTAMP NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS spots (
id_spots SERIAL NOT NULL PRIMARY KEY,
parking_id INT NOT NULL REFERENCES parkings(id_par) ON DELETE CASCADE,
spot_number INT NOT NULL UNIQUE,
status SMALLINT NOT NULL DEFAULT 1, -- 1 para disponible, 0 para ocupado
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- parkings
INSERT INTO parkings (name, location, total_spots, created_at, updated_at) VALUES
('Parking Central', 'Obrajes Calle 8', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Parking Norte', 'Obrajes Calle 2', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- spots
INSERT INTO spots (parking_id, spot_number, status, created_at, updated_at) VALUES
(1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 7, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 11, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 12, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 13, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 14, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 15, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 16, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
