### Obtener todas las reservas
GET http://localhost:8080/api/reservations

### Obtener una reserva por ID
GET http://localhost:8080/api/reservations/1

### Crear una nueva reserva
POST http://localhost:8080/api/reservations
Content-Type: application/json

{
  "userId": 1,
  "vehicleId": 1,
  "spotId": 1,
  "scheduledEntry": "2024-06-01T10:00:00",
  "scheduledExit": "2024-06-01T12:00:00",
  "status": "SCHEDULED"
}


### Eliminar una reserva por ID
DELETE http://localhost:8080/api/reservations/1
